[project]
name = "ggcmpy"
version = "0.0.1"
authors = [
  { name="Kai Germaschewski", email="kai.germaschewski@unh.edu" },
  { name="Jimmy Raeder", email="j.raeder@unh.edu" },
  { name="Matt Gilson" },
  { name="Kristofer Maynard" },
]
description = "Python utilities for the OpenGGCM Global Magnetosphere Code"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["numpy", "xarray"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/unh-hpc/ggcmpy"
Issues = "https://github.com/unh-hpc/ggcmpy/issues"

[build-system]
requires = ["scikit-build-core", "numpy"]
build-backend = "scikit_build_core.build"

[project.entry-points."xarray.backends"]
jrrle_engine = "ggcmpy.jrrle_backend:JrrleEntrypoint"
