[project]
name = "ggcmpy"
version = "0.0.1"
authors = [
  { name = "Kai Germaschewski", email = "kai.germaschewski@gmail.com" },
  { name = "Jimmy Raeder", email = "j.raeder@unh.edu" },
  { name = "Matt Gilson" },
  { name = "Kristofer Maynard" },
]
description = "Python utilities for the OpenGGCM Global Magnetosphere Code"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
  "Development Status :: 1 - Planning",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering",
]
dependencies = ["numpy", "xarray"]

[project.optional-dependencies]
test = ["pytest >=6", "pytest-cov >=3"]
dev = ["pytest >=6", "pytest-cov >=3"]
docs = [
  "sphinx>=7.0",
  "myst_parser>=0.13",
  "sphinx_copybutton",
  "sphinx_autodoc_typehints",
  "furo>=2023.08.17",
]

[project.urls]
Homepage = "https://github.com/unh-hpc/ggcmpy"
"Bug Tracker" = "https://github.com/unh-hpc/ggcmpy/issues"

[build-system]
requires = ["scikit-build-core", "numpy"]
build-backend = "scikit_build_core.build"

[project.entry-points."xarray.backends"]
jrrle_engine = "ggcmpy.jrrle_backend:JrrleEntrypoint"
